{
 "title": "Bull Queue Dashboard",
 "description": "Dashboard for bull queue metrics. To be used with https://hub.docker.com/r/ejhayes/nodejs-bull-monitor",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue_prefix",
    "label": "Queue Prefix",
    "query": {
     "query": "label_values(jobs_completed_total,queue_prefix)"
    }
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": {
     "query": "label_values(jobs_completed_total{queue_prefix=\"$queue_prefix\"}, queue_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Job Counts",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_waiting_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"} + jobs_delayed_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}",
     "legendFormat": "Total Waiting"
    },
    {
     "expr": "jobs_active_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}",
     "legendFormat": "Total Active"
    },
    {
     "expr": "jobs_failed_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}",
     "legendFormat": "Total Failed"
    }
   ]
  },
  {
   "title": "Current Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(job_name) (rate(jobs_active{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\"}[1m]) * 60)",
     "legendFormat": "Processed/minute"
    },
    {
     "expr": "sum without (job_name) (rate(jobs_completed{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\"}[1m]) * 60)",
     "legendFormat": "Completed/minute"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(jobs_failed{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\"}[1m]) * 60)",
     "legendFormat": "Failed/minute"
    }
   ]
  },
  {
   "title": "Processing Rates",
   "type": "graph",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "opm", "label": "Jobs Processes (jobs/minute)" }
   ],
   "targets": [
    {
     "expr": "sum without (job_name) (rate(jobs_active{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[1m]) * 60)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum without (job_name) (rate(jobs_completed{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[1m]) * 60)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum without (error_type) (rate(jobs_failed{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[1m]) * 60)",
     "legendFormat": "Failed"
    },
    {
     "expr": "jobs_waiting_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"} + jobs_delayed_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}",
     "legendFormat": "Total Waiting"
    },
    {
     "expr": "jobs_failed_total{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}",
     "legendFormat": "Total Failed"
    }
   ]
  },
  {
   "title": "Error rates by type",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "opm", "label": "Fail Rate (jobs/minute)" }
   ],
   "targets": [
    {
     "expr": "rate(jobs_failed{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\"}[1m]) * 60",
     "legendFormat": "{{job_name}}:{{error_type}}"
    }
   ]
  },
  { "title": "Job Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Completed Job Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_completed{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[$__range])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Failed Job Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job_name) (increase(jobs_failed{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[$__range]))",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Failed Job Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_failed{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\"}[$__range])",
     "legendFormat": "{{job_name}}:{{error_type}}"
    }
   ]
  },
  {
   "title": "Successful Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Job Duration" }
   ],
   "targets": [
    {
     "expr": "sum without (job_name) (job_duration{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\",quantile=~\"0.5|0.9|0.95|0.99\",status=\"completed\"})",
     "legendFormat": "duration:{{quantile}}"
    }
   ]
  },
  {
   "title": "Successful Job Wait Time (0.95 quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Wait Duration" }
   ],
   "targets": [
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"completed\"}[1m]) * 60)",
     "legendFormat": "{{status}}:wait[1m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"completed\"}[5m]) * 60)",
     "legendFormat": "{{status}}:wait[5m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"completed\"}[30m]) * 60)",
     "legendFormat": "{{status}}:wait[30m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"completed\"}[1h]) * 60)",
     "legendFormat": "{{status}}:wait[1h]"
    }
   ]
  },
  {
   "title": "Failed Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms", "label": "Job Duration" }
   ],
   "targets": [
    {
     "expr": "sum without (error_type, job_name) (job_duration{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\",quantile=~\"0.5|0.9|0.95|0.99\",status=\"failed\"})",
     "legendFormat": "duration:{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed Job Wait Time (0.95 quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms", "label": "Wait Duration" }
   ],
   "targets": [
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"failed\"}[1m]) * 60)",
     "legendFormat": "{{status}}:wait[1m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"failed\"}[5m]) * 60)",
     "legendFormat": "{{status}}:wait[5m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"failed\"}[30m]) * 60)",
     "legendFormat": "{{status}}:wait[30m]"
    },
    {
     "expr": "sum without (error_type, job_name) (rate(job_wait_duration{queue_name=\"$queue_name\",queue_prefix=\"$queue_prefix\",quantile=\"0.95\",status=\"failed\"}[1h]) * 60)",
     "legendFormat": "{{status}}:wait[1h]"
    }
   ]
  },
  {
   "title": "Attempts per job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Attempts Made" }
   ],
   "targets": [
    {
     "expr": "sum without(job_name) (job_attempts{queue_prefix=\"$queue_prefix\",queue_name=\"$queue_name\",quantile=~\"0.5|0.9|0.95|0.99\",status=\"completed\"})",
     "legendFormat": "attempts:{{quantile}}"
    }
   ]
  }
 ]
}