x-logging: &logging
  driver: json-file
  options:
    labels: service.name,service.namespace,otel.logs
    max-size: "10m"
    max-file: "3"

services:
  exportarr_sonarr:
    image: ghcr.io/onedr0p/exportarr:v2.1.0
    container_name: exportarr_sonarr
    logging: *logging
    labels:
      - service.name=exportarr_sonarr
      - service.namespace=observability
    command: sonarr
    environment:
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=${SONARR_API_KEY}
    healthcheck:
      disable: true
    networks:
      - traefik
    restart: unless-stopped

  exportarr_radarr:
    image: ghcr.io/onedr0p/exportarr:v2.1.0
    container_name: exportarr_radarr
    logging: *logging
    labels:
      - service.name=exportarr_radarr
      - service.namespace=observability
    command: radarr
    environment:
      - PORT=9708
      - URL=http://radarr:7878
      - APIKEY=${RADARR_API_KEY}
    healthcheck:
      disable: true
    networks:
      - traefik
    restart: unless-stopped

  exportarr_prowlarr:
    image: ghcr.io/onedr0p/exportarr:v2.1.0
    container_name: exportarr_prowlarr
    logging: *logging
    labels:
      - service.name=exportarr_prowlarr
      - service.namespace=observability
    command: prowlarr
    environment:
      - PORT=9709
      - URL=http://prowlarr:9696
      - APIKEY=${PROWLARR_API_KEY}
    healthcheck:
      disable: true
    networks:
      - traefik
    restart: unless-stopped

  exportarr_bazarr:
    image: ghcr.io/onedr0p/exportarr:v2.1.0
    container_name: exportarr_bazarr
    logging: *logging
    labels:
      - service.name=exportarr_bazarr
      - service.namespace=observability
    command: bazarr
    environment:
      - PORT=9710
      - URL=http://bazarr:6767
      - APIKEY=${BAZARR_API_KEY}
    healthcheck:
      disable: true
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
